---
# tasks file for application
- name: Create nginx dir
  ansible.builtin.file:
    path: "{{ app_dir_path }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ app_dir_path }}/docker-compose.yml"

- name: Docker-compose start
  ansible.builtin.command:
    cmd: " docker-compose -f {{ app_dir_path }}/docker-compose.yml up -d"

